volumes:
  postgres-volume:
    driver: local

services:
  spid-postgres:
    image: postgres:18.4
    restart: always
    container_name: "spid-postgres"
    networks:
      - spid-local-network
    environment:
      POSTGRES_DB: ${SPID_DB_SCHEMA}
      POSTGRES_USER: ${SPID_DB_USERNAME}
      POSTGRES_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/18/docker
  spid-keycloak:
    image: quay.io/keycloak/keycloak:${SPID_KC_VERSION}
    restart: always
    container_name: "spid-keycloak"
    command: "start-dev --import-realm --verbose"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "info"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SPID_KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SPID_KC_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      DB: postgres
      DB_URL_HOST: spid-postgres
      DB_SCHEMA: ${SPID_DB_SCHEMA}
      DB_USERNAME: ${SPID_DB_USERNAME}
      DB_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - ./realm:/opt/keycloak/data/import
      - ./provider/spid-provider.jar:/opt/keycloak/providers/spid-provider.jar
      - ./certificates/keycloak-server.p12:/opt/keycloak/conf/server.keystore.p12
    networks:
      - spid-local-network
    depends_on:
      - spid-postgres

networks:
  spid-local-network:
    driver: bridge
