# Common spid-keycloak service; ${SPID_KC_DB_TYPE} environment variable can be set to match the db used in the infrastructure

services:
  spid-keycloak:
    image: quay.io/keycloak/keycloak:${SPID_KC_VERSION}
    restart: always
    container_name: "spid-keycloak"
    command: "start-dev --import-realm --verbose"
    ports:
      - 8080:8080 # Standard http
      - 8443:8443 # Standard https
      - 8787:8787 # Debug
    environment:
      KC_DEBUG: "true"
      KC_DEBUG_PORT: "*:8787"
      KC_LOG_LEVEL: "info"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SPID_KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SPID_KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      KC_HOSTNAME_STRICT: "false"
      DB: ${SPID_KC_DB_TYPE}
      DB_URL_HOST: spid-${SPID_KC_DB_TYPE}
      DB_SCHEMA: ${SPID_DB_SCHEMA}
      DB_USERNAME: ${SPID_DB_USERNAME}
      DB_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - type: bind
        source: ./realm
        target: /opt/keycloak/data/import
        read_only: "true"
      - type: bind
        source: ./provider/spid-provider.jar
        target: /opt/keycloak/providers/spid-provider.jar
        read_only: "true"
      - type: bind
        source: ./certificates/keycloak-server.crt.pem
        target: /opt/keycloak/conf/server.crt.pem
        read_only: "true"
      - type: bind
        source: ./certificates/keycloak-server.key.pem
        target: /opt/keycloak/conf/server.key.pem
        read_only: "true"
      - type: bind
        source: ./certificates/spid-saml-check.crt
        target: /opt/keycloak/conf/truststores/spid-saml-check.crt
        read_only: "true"
    networks:
      - spid-local-network
    depends_on:
      - spid-${SPID_KC_DB_TYPE}
