# Common spid-keycloak service; ${SPID_KC_DB_TYPE} environment variable can be set to match the db used in the infrastructure

services:
  spid-nginx:
    image: nginx:1.31.1
    container_name: "spid-nginx"
    ports:
      - 80:80 # Standard http
      - 443:443 # Standard https
    volumes:
      - ./tests/spid-sp-test.xml:/usr/share/nginx/html/spid-sp-test.xml:ro
      - ./certificates/nginx.crt:/etc/ssl/certs/nginx.crt:ro
      - ./certificates/nginx.key:/etc/ssl/private/nginx.key:ro
      - ./nginx/secure-nginx.conf:/etc/nginx/conf.d/secure-nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--fail", "https://localhost:443"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - spid-local-network
