volumes:
  mariadb-volume:
    driver: local

services:
  spid-mariadb:
    image: mariadb:10.5.29 # Ultima versione con default unicode utf8mb3
    restart: always
    container_name: "spid-mariadb"
    networks:
      - spid-local-network
    environment:
      MYSQL_ROOT_PASSWORD: ${SPID_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SPID_DB_SCHEMA}
      MYSQL_USER: ${SPID_DB_USERNAME}
      MYSQL_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - mariadb-volume:/var/lib/mysql
