volumes:
  postgres-volume:
    driver: local

services:
  spid-postgres:
    image: postgres:18.4
    restart: always
    container_name: "spid-postgres"
    networks:
      - spid-local-network
    environment:
      POSTGRES_DB: ${SPID_DB_SCHEMA}
      POSTGRES_USER: ${SPID_DB_USERNAME}
      POSTGRES_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/18/docker
