# Common spid-keycloak service; ${SPID_KC_DB_TYPE} environment variable can be set to match the db used in the infrastructure

services:
  spid-keycloak:
    image: quay.io/keycloak/keycloak:${SPID_KC_VERSION}
    container_name: "spid-keycloak"
    command: "start-dev --import-realm --verbose"
    ports:
      - 8080:8080 # Standard http
      - 8443:8443 # Standard https
      - 8787:8787 # Debug
      - 9000:9000 # Monitoring / OpenAPI
    environment:
      KC_DEBUG: "true"
      KC_DEBUG_PORT: "*:8787"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "info"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SPID_KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SPID_KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: "/auth" # For backwards compatibility
      DB: ${SPID_KC_DB_TYPE}
      DB_URL_HOST: spid-${SPID_KC_DB_TYPE}
      DB_SCHEMA: ${SPID_DB_SCHEMA}
      DB_USERNAME: ${SPID_DB_USERNAME}
      DB_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - ./realm:/opt/keycloak/data/import:ro
      - ./provider/spid-provider.jar:/opt/keycloak/providers/spid-provider.jar:ro
      - ./certificates/keycloak-server.crt:/opt/keycloak/conf/server.crt:ro
      - ./certificates/keycloak-server.key:/opt/keycloak/conf/server.key:ro
      - ./certificates/nginx.crt:/opt/keycloak/conf/truststores/nginx.crt:ro
    networks:
      - spid-local-network
    depends_on:
      - spid-${SPID_KC_DB_TYPE}
