volumes:
  mysql-volume:
    driver: local

services:
  spid-mysql:
    image: mysql:5.7.44 # Ultima versione con default unicode utf8mb3
    restart: always
    container_name: "spid-mysql"
    networks:
      - spid-local-network
    environment:
      MYSQL_ROOT_PASSWORD: ${SPID_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SPID_DB_SCHEMA}
      MYSQL_USER: ${SPID_DB_USERNAME}
      MYSQL_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql
  spid-keycloak:
    image: quay.io/keycloak/keycloak:${SPID_KC_VERSION}
    restart: always
    container_name: "spid-keycloak"
    command: "start-dev --import-realm"
    ports:
      - 8180:8180
    environment:
      KC_HTTP_PORT: "8180"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "info"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SPID_KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SPID_KC_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      DB: mysql
      DB_URL_HOST: spid-mysql
      DB_SCHEMA: ${SPID_DB_SCHEMA}
      DB_USERNAME: ${SPID_DB_USERNAME}
      DB_PASSWORD: ${SPID_DB_PASSWORD}
    volumes:
      - ./realm:/opt/keycloak/data/import
      - ./provider/spid-provider.jar:/opt/keycloak/providers/spid-provider.jar
    networks:
      - spid-local-network
    depends_on:
      - spid-mysql

networks:
  spid-local-network:
    driver: bridge
